import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/core-concepts',
        'getting-started/your-first-bridge',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'tutorials/index',
      },
      items: [
        {
          type: 'category',
          label: 'Beginner',
          items: [
            'tutorials/beginner/simple-bridge',
            'tutorials/beginner/using-middleware',
            'tutorials/beginner/multi-provider',
            'tutorials/beginner/building-chat-api',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Architecture',
          items: [
            'guides/architecture/ir-format',
          ],
        },
        {
          type: 'category',
          label: 'Testing',
          link: {
            type: 'doc',
            id: 'guides/testing/index',
          },
          items: [],
        },
      ],
    },
    {
      type: 'category',
      label: 'Integration Patterns',
      link: {
        type: 'doc',
        id: 'patterns/index',
      },
      items: [],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'api/index',
      },
      items: [
        'api/bridge',
        'api/router',
        'api/middleware',
        'api/types',
        'api/errors',
      ],
    },
    {
      type: 'category',
      label: 'Complete API Reference',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'api/generated/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/generated',
        },
      ],
    },
    {
      type: 'category',
      label: 'Packages',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'packages/overview',
      },
      items: [
        {
          type: 'doc',
          id: 'api/all-packages',
          label: 'All Packages Overview',
        },
        {
          type: 'category',
          label: 'Core',
          collapsed: true,
          items: [
            'api/packages/ai.matey',
            'api/packages/ai.matey.core',
            'api/packages/ai.matey.types',
            'api/packages/ai.matey.errors',
            'api/packages/ai.matey.utils',
            'api/packages/ai.matey.testing',
          ],
        },
        {
          type: 'category',
          label: 'Adapters',
          collapsed: true,
          items: [
            'api/packages/backend',
            'api/packages/frontend',
            'api/packages/backend-browser',
          ],
        },
        {
          type: 'category',
          label: 'Middleware',
          collapsed: true,
          items: [
            'api/packages/middleware',
          ],
        },
        {
          type: 'category',
          label: 'HTTP',
          collapsed: true,
          items: [
            'api/packages/http',
            'api/packages/http.core',
          ],
        },
        {
          type: 'category',
          label: 'React',
          collapsed: true,
          items: [
            'api/packages/react-core',
            'api/packages/react-hooks',
            'api/packages/react-stream',
            'api/packages/react-nextjs',
          ],
        },
        {
          type: 'category',
          label: 'Native',
          collapsed: true,
          items: [
            'api/packages/native-apple',
            'api/packages/native-node-llamacpp',
            'api/packages/native-model-runner',
          ],
        },
        {
          type: 'category',
          label: 'Utilities',
          collapsed: true,
          items: [
            'api/packages/wrapper',
            'api/packages/cli',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'contributing/index',
      },
      items: [
        'contributing/development',
        'contributing/architecture',
      ],
    },
  ],
  examples: [
    {
      type: 'doc',
      id: 'examples/index',
      label: 'Examples Overview',
    },
  ],
};

export default sidebars;
